Added brazilian portuguese translation
mmatyas/pegasus-frontend-translations pull request #5
Opened 2018-12-02 12:05 UTC by rutantan

2018-12-03 18:47 UTC, mmatyas requested changes
Thank you! Looks good, I've only marked a few minor issues below:

2018-12-03 18:47 UTC, mmatyas commented on pegasus_pt-br.ts
> +        <translation type="unfinished"></translation>
The translation seems to be missing here.

2018-12-03 18:47 UTC, mmatyas commented on translations.qrc.in
> +		<file>pegasus_pt-br.qm</file>
Use spaces here for the indentation.

2018-12-03 18:47 UTC, mmatyas commented on pegasus_pt-br.ts
> +<?xml version="1.0" encoding="utf-8"?>
The file should be called `pegasus_pt-BR.ts` (ie. capital `BR`).

2018-12-03 20:35 UTC, rutantan commented on pegasus_pt-br.ts
> +        <translation type="unfinished"></translation>
```suggestion
        <translation>Idioma</translation>
```

2018-12-03 20:37 UTC, rutantan commented on translations.qrc.in
> +		<file>pegasus_pt-br.qm</file>
```suggestion
        <file>pegasus_pt-br.qm</file>
```

2018-12-03 20:39 UTC, rutantan commented
Will create a new pull request as I don't know how to change the file name here.

2018-12-03 20:44 UTC, rutantan reviewed
Updates to brazilian portuguese language.

2018-12-04 10:52 UTC, mmatyas approved these changes

2018-12-04 10:53 UTC, mmatyas commented
Thanks! Just one last thing, could you merge all the separate commits into a single one?

2018-12-05 01:50 UTC, rutantan commented
How can I do that?

Em ter, 4 de dez de 2018 às 08:53, Mátyás Mustoha <notifications@github.com>
escreveu:

> Thanks! Just one last thing, could you merge all the separate commits into
> a single one?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mmatyas/pegasus-frontend-translations/pull/5#issuecomment-444058563>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVNuJAJmSLKQEn2yKEGs0rrB23f-brH5ks5u1lQwgaJpZM4Y9XuQ>
> .
>

2018-12-05 13:47 UTC, mmatyas commented
If you're using Git from the terminal, you can `git rebase -i HEAD~5` (`i` for interactive editing, of `HEAD~5`, the last five commits). An editor will pop up, and you should mark all commits other than the first one as fixup/`f`, like this:

![screenshot_2018-12-05_14-39-57](https://user-images.githubusercontent.com/4354863/49517118-acf29b00-f89b-11e8-9f35-6847a44c0cc7.png)

Save, then `git push --force`.

If you're using a GUI, there should be similar rebasing tools in it too.

Alternatively I can also do this merging for you if you wish.

2018-12-05 17:38 UTC, rutantan commented
Thank you!
I've done it, it should be merged by now.

Em qua, 5 de dez de 2018 às 11:47, Mátyás Mustoha <notifications@github.com>
escreveu:

> If you're using Git from the terminal, you can git rebase -i HEAD~5 (i
> for interactive editing, of HEAD~5, the last five commits). An editor
> will pop up, and you should mark all commits other than the first one as
> fixup/f, like this:
>
> [image: screenshot_2018-12-05_14-39-57]
> <https://user-images.githubusercontent.com/4354863/49517118-acf29b00-f89b-11e8-9f35-6847a44c0cc7.png>
>
> Save, then git push --force.
>
> If you're using a GUI, there should be similar rebasing tools in it too.
>
> Alternatively I can also do this merging for you if you wish.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mmatyas/pegasus-frontend-translations/pull/5#issuecomment-444490656>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVNuJN7INn5v8SHRJSYH6tK4uuGl1Xzxks5u186IgaJpZM4Y9XuQ>
> .
>

2018-12-05 19:14 UTC, merged

2018-12-05 19:17 UTC, mmatyas commented
Ok, language added, will appear in the next update of Pegasus. Thanks again!